### ISSUE TITLE
use UIWebView will no longer be accepted as of December 2020

### ISSUE THREAD

**Issue by AlexSeverinov** [freshbits/pathshare-sdk-ios#10]
Hi!
Could you check that yours SDK not use UIWebView cause it will no longer be accepted as of December 2020.

![Screenshot 2020-06-12 at 16 02 44](https://user-images.githubusercontent.com/3671476/84505697-dc6f3880-acc6-11ea-8658-b9f22c3eac7a.png)

**Comment by endruuu** [comment]
@jhabr Any updates on this?

**Comment by jhabr** [comment]
@endruuu we're looking into this issue and an update of the SDK will be available soon.

**Comment by jhabr** [comment]
@endruuu we updated the SDK to `2.3.3`:
https://github.com/freshbits/pathshare-sdk-ios/releases/tag/2.3.3

Also see the change log for changes:
https://github.com/freshbits/pathshare-sdk-ios/blob/2.3.3/CHANGELOG.md

Wanna give it a try?

**Comment by endruuu** [comment]
@jhabr we have tried it and it looks good. Thank you so much for your support!
