### ISSUE TITLE
Build framework with bitcode support

### ISSUE THREAD

**Issue by AlexSeverinov** [freshbits/pathshare-sdk-ios#6]
![screen shot](https://user-images.githubusercontent.com/3671476/50344570-3c52ac00-0534-11e9-948f-78fdd354722f.png)

**Comment by jhabr** [comment]
Hi Alex

Thanks for your feedback, will add bitcode support shortly.

**Comment by jhabr** [comment]
@AlexSeverinov support for bitcode added in version 2.3.1.

**Comment by AlexSeverinov** [comment]
Thanks Jaro!

**Comment by AlexSeverinov** [comment]
Hi Jaro
Faced with same issue in version 2.3.1
`otool -l PathshareSDK.framework/PathshareSDK | grep __LLVM` - return nothing

You could check how it must looks in this framework https://github.com/CardConnect/ios-sdk (Release)

**Comment by AlexSeverinov** [comment]
Maybe this topic will be helpful  https://medium.com/curofy-engineering/creating-your-custom-objective-c-framework-for-ios-apps-5d5ccf95c6c7, section `Uploading the app with framework on App Store :`

**Comment by jhabr** [comment]
Hi Alex,
thanks for the feedback, I'm looking into this issue again.

**Comment by jhabr** [comment]
Alex, if I run:
`otool -l -arch arm64 -arch armv7 PathshareSDK.framework/PathshareSDK | grep __LLVM`

... with specific arch types, I get the following: 
```
  segname __LLVM
   segname __LLVM
  segname __LLVM
   segname __LLVM
```

So bitcode should be already enabled with the `2.3.1` version.

Are you using cocoapods?

**Comment by AlexSeverinov** [comment]
I'm using cocoapods also tried add it as embedded framework

**Comment by AlexSeverinov** [comment]
I believe you could try to add Pathshare framework to any proj with bitcode support (`Enable Bitcode` to Yes in `ios-example-app` for instance) and try `Archive` and you see this issue

**Comment by AlexSeverinov** [comment]
![screen shot 2019-01-08 at 7 08 49 pm](https://user-images.githubusercontent.com/3671476/50847694-e5920280-137a-11e9-9f1d-b2ac749e369a.png)

**Comment by jhabr** [comment]
Hi Alex

Thanks for your answer. I've updated the framework. Creating an archive works now with `bitcode` enabled.

<img width="1364" alt="screenshot 2019-01-08 at 21 31 56" src="https://user-images.githubusercontent.com/25850/50857138-05322680-138d-11e9-8fd1-f70b5c6a7108.png">

Wanna give it another try?

**Comment by AlexSeverinov** [comment]
Thanks Jaro
